version: '3'
services:

  eureka-serviceregistry:
    container_name: eureka
    build: ./eureka
    ports:
      - "8761:8761"
    tty: true

  zuul:
    container_name: zuul
    build: ./zuul
    ports:
      - "8083:8083"
    environment:
      - REGISTRY_HOST=eureka-serviceregistry
    tty: true
    depends_on:
      - eureka-serviceregistry

  advertisement:
    container_name: advertisement
    build: ./advertisement
    ports:
      - "8084:8084"
    environment:
      - REGISTRY_HOST=eureka-serviceregistry
    tty: true
    depends_on:
      - eureka-serviceregistry

  authentication:
    container_name: authentication
    build: ./authentication
    ports:
      - "8085:8085"
    environment:
      - REGISTRY_HOST=eureka-serviceregistry
    tty: true
    depends_on:
      - eureka-serviceregistry

  location:
    container_name: location
    build: ./location
    ports:
      - "8086:8086"
    environment:
      - REGISTRY_HOST=eureka-serviceregistry
    tty: true
    depends_on:
      - eureka-serviceregistry

  messages:
    container_name: messages
    build: ./messages
    ports:
      - "8087:8087"
    environment:
      - REGISTRY_HOST=eureka-serviceregistry
    tty: true
    depends_on:
      - eureka-serviceregistry

  rent:
    container_name: rent
    build: ./rent
    ports:
      - "8088:8088"
    environment:
      - REGISTRY_HOST=eureka-serviceregistry
    tty: true
    depends_on:
      - eureka-serviceregistry

  search:
    container_name: search
    build: ./search
    ports:
      - "8089:8089"
    environment:
      - REGISTRY_HOST=eureka-serviceregistry
    tty: true
    depends_on:
      - eureka-serviceregistry

  statistics:
    container_name: statistics
    build: ./statistics
    ports:
      - "8090:8090"
    environment:
      - REGISTRY_HOST=eureka-serviceregistry
    tty: true
    depends_on:
      - eureka-serviceregistry