zuul:
  routes:
    advertisement:
      path: /advertisement/**
      stripPrefix: false
      serviceId: advertisement
    authentication:
      path: /auth/**
      stripPrefix: false
      serviceId: authentication
    rent:
      path: /rentRequest/**
      stripPrefix: false
      serviceId: rent
    location:
      path: /test/**
      stripPrefix: false
      serviceId: location
#    messages:
#      path: /test/**
#      stripPrefix: false
#      serviceId: messages
#    search:
#      path: /test/**
#      stripPrefix: false
#      serviceId: search
#    statistics:
#      path: /test/**
#      stripPrefix: false
#      serviceId: statistics