zuul:
  routes:
    advertisement_codebook:
      path: /codebook/**
      stripPrefix: false
      serviceId: advertisement
    advertisement_advertisement:
      path: /advertisement/**
      stripPrefix: false
      serviceId: advertisement
    advertisement_car:
      path: /car/**
      stripPrefix: false
      serviceId: advertisement
    authentication_user:
      path: /user/**
      stripPrefix: false
      serviceId: authentication
    authentication_auth:
      path: /auth/**
      stripPrefix: false
      serviceId: authentication
    rent_rentRequest:
      path: /rentRequest/**
      stripPrefix: false
      serviceId: rent
    rent_requestHolder:
      path: /requestHolder/**
      stripPrefix: false
      serviceId: rent
    location:
      path: /test/**
      stripPrefix: false
      serviceId: location
#    messages:
#      path: /test/**
#      stripPrefix: false
#      serviceId: messages
#    search:
#      path: /test/**
#      stripPrefix: false
#      serviceId: search
#    statistics:
#      path: /test/**
#      stripPrefix: false
#      serviceId: statistics
