//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.20 at 05:32:31 PM CEST 
//


package com.rent.soap.code;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="advertisementId" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="holderId" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "advertisementId",
        "holderId"
})
@XmlRootElement(name = "physicalRentResponse")
public class PhysicalRentResponse {

    protected long advertisementId;
    protected long holderId;

    /**
     * Gets the value of the advertisementId property.
     */
    public long getAdvertisementId() {
        return advertisementId;
    }

    /**
     * Sets the value of the advertisementId property.
     */
    public void setAdvertisementId(long value) {
        this.advertisementId = value;
    }

    /**
     * Gets the value of the holderId property.
     */
    public long getHolderId() {
        return holderId;
    }

    /**
     * Sets the value of the holderId property.
     */
    public void setHolderId(long value) {
        this.holderId = value;
    }

}
