//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.20 at 12:41:41 PM CEST 
//


package com.rent.soap.code;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RentRequests complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="RentRequests"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="version" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="startDateTime" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="endDateTime" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="rentRequestStatus" type="{http://localhost:8095/microservices/rent}rentRequestStatus" minOccurs="0"/&gt;
 *         &lt;element name="senderId" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="advertisementId" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="requests" type="{http://localhost:8095/microservices/rent}requestsHolder" minOccurs="0"/&gt;
 *         &lt;element name="created" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RentRequests", propOrder = {
        "id",
        "version",
        "startDateTime",
        "endDateTime",
        "rentRequestStatus",
        "senderId",
        "advertisementId",
        "requests",
        "created"
})
public class RentRequests {

    protected Long id;
    protected Long version;
    protected String startDateTime;
    protected String endDateTime;
    @XmlSchemaType(name = "string")
    protected RentRequestStatus rentRequestStatus;
    protected Long senderId;
    protected Long advertisementId;
    protected RequestsHolder requests;
    protected String created;

    /**
     * Gets the value of the id property.
     *
     * @return possible object is
     * {@link Long }
     */
    public Long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value allowed object is
     *              {@link Long }
     */
    public void setId(Long value) {
        this.id = value;
    }

    /**
     * Gets the value of the version property.
     *
     * @return possible object is
     * {@link Long }
     */
    public Long getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     *
     * @param value allowed object is
     *              {@link Long }
     */
    public void setVersion(Long value) {
        this.version = value;
    }

    /**
     * Gets the value of the startDateTime property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getStartDateTime() {
        return startDateTime;
    }

    /**
     * Sets the value of the startDateTime property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setStartDateTime(String value) {
        this.startDateTime = value;
    }

    /**
     * Gets the value of the endDateTime property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getEndDateTime() {
        return endDateTime;
    }

    /**
     * Sets the value of the endDateTime property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setEndDateTime(String value) {
        this.endDateTime = value;
    }

    /**
     * Gets the value of the rentRequestStatus property.
     *
     * @return possible object is
     * {@link RentRequestStatus }
     */
    public RentRequestStatus getRentRequestStatus() {
        return rentRequestStatus;
    }

    /**
     * Sets the value of the rentRequestStatus property.
     *
     * @param value allowed object is
     *              {@link RentRequestStatus }
     */
    public void setRentRequestStatus(RentRequestStatus value) {
        this.rentRequestStatus = value;
    }

    /**
     * Gets the value of the senderId property.
     *
     * @return possible object is
     * {@link Long }
     */
    public Long getSenderId() {
        return senderId;
    }

    /**
     * Sets the value of the senderId property.
     *
     * @param value allowed object is
     *              {@link Long }
     */
    public void setSenderId(Long value) {
        this.senderId = value;
    }

    /**
     * Gets the value of the advertisementId property.
     *
     * @return possible object is
     * {@link Long }
     */
    public Long getAdvertisementId() {
        return advertisementId;
    }

    /**
     * Sets the value of the advertisementId property.
     *
     * @param value allowed object is
     *              {@link Long }
     */
    public void setAdvertisementId(Long value) {
        this.advertisementId = value;
    }

    /**
     * Gets the value of the requests property.
     *
     * @return possible object is
     * {@link RequestsHolder }
     */
    public RequestsHolder getRequests() {
        return requests;
    }

    /**
     * Sets the value of the requests property.
     *
     * @param value allowed object is
     *              {@link RequestsHolder }
     */
    public void setRequests(RequestsHolder value) {
        this.requests = value;
    }

    /**
     * Gets the value of the created property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getCreated() {
        return created;
    }

    /**
     * Sets the value of the created property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setCreated(String value) {
        this.created = value;
    }

}
