//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.21 at 12:09:07 AM CEST 
//


package com.statistics.soap.code;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="date" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="dateString" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="content" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="advertisement_id" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="commenter_id" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="commenter" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="rent_request_id" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "id",
        "date",
        "dateString",
        "content",
        "status",
        "advertisementId",
        "commenterId",
        "commenter",
        "rentRequestId"
})
@XmlRootElement(name = "commentRequest")
public class CommentRequest {

    protected Long id;
    protected String date;
    protected String dateString;
    protected String content;
    protected String status;
    @XmlElement(name = "advertisement_id")
    protected Long advertisementId;
    @XmlElement(name = "commenter_id")
    protected Long commenterId;
    protected String commenter;
    @XmlElement(name = "rent_request_id")
    protected Long rentRequestId;

    /**
     * Gets the value of the id property.
     *
     * @return possible object is
     * {@link Long }
     */
    public Long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value allowed object is
     *              {@link Long }
     */
    public void setId(Long value) {
        this.id = value;
    }

    /**
     * Gets the value of the date property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getDate() {
        return date;
    }

    /**
     * Sets the value of the date property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDate(String value) {
        this.date = value;
    }

    /**
     * Gets the value of the dateString property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getDateString() {
        return dateString;
    }

    /**
     * Sets the value of the dateString property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDateString(String value) {
        this.dateString = value;
    }

    /**
     * Gets the value of the content property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getContent() {
        return content;
    }

    /**
     * Sets the value of the content property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setContent(String value) {
        this.content = value;
    }

    /**
     * Gets the value of the status property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the advertisementId property.
     *
     * @return possible object is
     * {@link Long }
     */
    public Long getAdvertisementId() {
        return advertisementId;
    }

    /**
     * Sets the value of the advertisementId property.
     *
     * @param value allowed object is
     *              {@link Long }
     */
    public void setAdvertisementId(Long value) {
        this.advertisementId = value;
    }

    /**
     * Gets the value of the commenterId property.
     *
     * @return possible object is
     * {@link Long }
     */
    public Long getCommenterId() {
        return commenterId;
    }

    /**
     * Sets the value of the commenterId property.
     *
     * @param value allowed object is
     *              {@link Long }
     */
    public void setCommenterId(Long value) {
        this.commenterId = value;
    }

    /**
     * Gets the value of the commenter property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getCommenter() {
        return commenter;
    }

    /**
     * Sets the value of the commenter property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setCommenter(String value) {
        this.commenter = value;
    }

    /**
     * Gets the value of the rentRequestId property.
     *
     * @return possible object is
     * {@link Long }
     */
    public Long getRentRequestId() {
        return rentRequestId;
    }

    /**
     * Sets the value of the rentRequestId property.
     *
     * @param value allowed object is
     *              {@link Long }
     */
    public void setRentRequestId(Long value) {
        this.rentRequestId = value;
    }

}
